TRUNCATE TABLE 
  ai_model_invocations,
  agent_actions,
  capabilities,
  capability_levels,
  career_paths,
  companies,
  conversation_sessions,
  chat_messages,
  divisions,
  general_roles,
  general_role_types,
  institutions,
  jobs,
  job_documents,
  job_skills,
  jobs_history,
  profile_agent_actions,
  profile_capabilities,
  profile_career_paths,
  profile_job_interactions,
  profile_skills,
  profiles,
  role_capabilities,
  role_documents,
  role_skills,
  role_taxonomies,
  roles,
  skills,
  taxonomy,
  users
RESTART IDENTITY CASCADE;

